name: Build & Test

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'bin/*'
      - 'screenshot'
      - 'scripts'
      - 'src'
      - 'test'
      - 'types'
      - 'package.json'

jobs:
  build_and_test:
    strategy:
      fail-fast: false # turn off for testing
      matrix:
        node: [12]
        os: ['ubuntu-latest']

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}.x
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}.x

      - name: install
        run: npm install

      - name: build
        run: npm run build -- --ci

      - name: test dist
        run: npm run test.dist && npm run test.testing

      - name: test end-to-end
        run: npm run test.end-to-end -- --ci

      - name: test jest
        run: npm run test.jest -- --maxWorkers=1

      - name: test sys-node
        run: npm run test.sys.node

      - name: pack
        run: mv `npm pack` stencil-build.tgz

      - uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12'
        with:
          name: stencil-build
          path: stencil-build.tgz

      - name: Run karma
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12'
        run: |
          wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
          unzip BrowserStackLocal-linux-x64.zip
          ./BrowserStackLocal -k $BROWSER_STACK_ACCESS_KEY &
          cd ./test/karma && npm install
          cd ./test/karma && npm run karma.prod
